---
abstract: 'An interface to the Open Data API of Gothenburg'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  XML::LibXML: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OpenGbg
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Config::Any: '0'
  DateTime: '0'
  DateTime::Format::HTTP: '0'
  File::HomeDir: '0'
  HTTP::Tiny: '0'
  Kavorka: '0'
  Moops: '0'
  Moose: '0'
  MooseX::AttributeShortcuts: '0'
  Path::Tiny: '0'
  Sub::Exporter: '0'
  Syntax::Feature::Qs: '0'
  Throwable::X: '0'
  Type::Tiny: '0'
  Types::DateTime: '0'
  Types::Path::Tiny: '0'
  XML::LibXML: '0'
  XML::Rabbit: '0'
  perl: '5.014000'
version: '0.1100'
